name:  GH Actions 1st workflow
on:
    push:
       branches:
         - main    
jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
        - name: Check Repo
          uses: actions/checkout@v4
        - name: List and Read file
          run: | 
            echo "This is the 1st Githbu Action Job"  
            ls -ltra
            cat README.md
        - name: Add the new items to README.md
          run: | 
            echo "# 4. Call resusable workflow from another repository" | tee >> README.md  
          
         

            
            
  #      #       - name: List files
  #      #       - name: List files
  #      #       - name: List files     



      
